# multi-variable Linear Regression 
regression using three inputs (x1, x2, x3) <br>
multi-variable/feature <br>
**x1, x2, x2 and Y** <br>
<br>
<br>
\\(H(x) = Wx + b\\)<br> 

\\(H(x_{1}, x_{2}, x_{3}) = W_{1}x_{1} + W_{2}x_{2} + W_{3}x_{3} + b\\)<hr><br> 
<br>
\\(cost(W, b)\\) = \\(\frac{1}{m}\sum_{i=1}^{m} (H(x^i)-y^i)^2\\) <br>
\\(cost(W, b)\\) = \\(\frac{1}{m}\sum_{i=1}^{m} H(x_{1}^{(i)}, x_{2}^{(i)}, x_{3}^{(i)})-y^{(i)})^2\\) <br>

## Matrix
## 1. Matrix multiplication
## 2. Hypothesis using matrix
\\(w_{1}x_{1}+w_{2}x_{2}+w_{3}x_{3}+ ... + w_{n}x_{n}\\)
<br>
\\((x_{1}, x_{2}, x_{3})
 \begin{pmatrix}
  w_{1} \\
  w_{2} \\
  w_{3} \\
 \end{pmatrix}\\)
 <br>
 \\(H(X) = XW \\)
 > matrix를 쓸 때는 보통 x를 앞에다 쓴다.
 
 ### 1. Many x instances
 데이터가 3개 <br>
 많은 인스턴스들이 있을 때, <br>
 * <u> 인스턴스가 만개일 때, </u> <br>
 \\((x_{1}, x_{2}, x_{3})
 \begin{pmatrix}
  w_{1} \\
  w_{2} \\
  w_{3} \\
 \end{pmatrix}\\)
 <br>
 이것을 만번 반복 <br><br>
 
 * <u> 인스턴스 수대로 매트릭스를 준다. </u><br>
 인스턴스가 5개 였을 경우, <br>
 \\( \begin{pmatrix}
  x_{11} x_{12} x{13} \\
  x_{21} x_{22} x{23} \\
  x_{31} x_{32} x{33} \\
  x_{41} x_{42} x{43} \\
  x_{51} x_{52} x{53} \\
 \end{pmatrix} * 
 \begin{pmatrix}
  w_{1} \\
  w_{2} \\
  w_{3} \\
  w_{4} \\
  w_{5} \\
 \end{pmatrix}\\)
 <br>
 [5, 3] * [3, 1] = <br>\\([인스턴스 5개 * y의 variable의 갯수] * [데이터에 대한 weigt * 1]\\)<br>
 \\([인스턴스 5개 * 3개의 x feature] * [데이터에 대한 weigt * 1]\\)
 <br><br>
 * =====인스턴스 갯수가 n개일 때 ===== <br>
 numpy에서는 <br> 
 [-1, x의 feature]<br>
 tensor에서는 <br>
 [None, x의 feature]
 

In [1]:
import tensorflow as tf

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## \\(H(x1, x2, x3) = w_{1}x_{1}+w_{2}x_{2}+w_{3}x_{3}\\)

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [4]:
cost = tf.reduce_mean(tf.square(hypothesis - Y)) # hyopothesis와 Y차이를 평균
optimizer = tf.train.GradientDescentOptimizer(learning_rate =1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nprediction:\n", hy_val)

0 Cost:  27945.13 
prediction:
 [8.049596  3.4288151 7.0267158 2.6177647 5.1811194]
10 Cost:  8.686878 
prediction:
 [155.89769 181.1482  182.12775 193.30032 140.73888]
20 Cost:  8.402875 
prediction:
 [156.33604 181.69202 182.65471 193.87608 141.1563 ]
30 Cost:  8.374708 
prediction:
 [156.32838 181.69975 182.65343 193.87662 141.1648 ]
40 Cost:  8.34678 
prediction:
 [156.31941 181.7058  182.65054 193.87541 141.17203]
50 Cost:  8.318964 
prediction:
 [156.31044 181.71184 182.64766 193.87418 141.17921]
60 Cost:  8.29126 
prediction:
 [156.3015  181.7179  182.64484 193.873   141.18642]
70 Cost:  8.263771 
prediction:
 [156.2926  181.7239  182.64201 193.87183 141.1936 ]
80 Cost:  8.236389 
prediction:
 [156.28372 181.72992 182.63918 193.87064 141.20074]
90 Cost:  8.2091465 
prediction:
 [156.27487 181.73593 182.63635 193.86945 141.20789]
100 Cost:  8.1820135 
prediction:
 [156.26602 181.74191 182.63354 193.86829 141.215  ]
110 Cost:  8.15509 
prediction:
 [156.2572  181.74783 182.63074 1

1070 Cost:  6.110907 
prediction:
 [155.50856 182.25275 182.3907  193.77568 141.81537]
1080 Cost:  6.0943246 
prediction:
 [155.5017  182.25737 182.38847 193.77496 141.8207 ]
1090 Cost:  6.0779295 
prediction:
 [155.49486 182.26195 182.38625 193.77419 141.82603]
1100 Cost:  6.061546 
prediction:
 [155.48802 182.26656 182.38406 193.77345 141.83134]
1110 Cost:  6.045227 
prediction:
 [155.4812  182.27115 182.38188 193.77274 141.83667]
1120 Cost:  6.02903 
prediction:
 [155.4744  182.27573 182.37968 193.77196 141.84193]
1130 Cost:  6.012898 
prediction:
 [155.46764 182.28029 182.37749 193.77124 141.84721]
1140 Cost:  5.996919 
prediction:
 [155.46086 182.2848  182.37532 193.77046 141.85246]
1150 Cost:  5.9808836 
prediction:
 [155.45413 182.28937 182.37312 193.76978 141.85771]
1160 Cost:  5.9649477 
prediction:
 [155.4474  182.29391 182.37096 193.76907 141.86293]
1170 Cost:  5.9492135 
prediction:
 [155.4407  182.2984  182.36879 193.76831 141.86816]
1180 Cost:  5.9334555 
prediction:
 [15

##  \\(H(X) = XW \\)

In [15]:
x_data = [[73., 80., 75.], # 하나의 인스턴스
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3]) # 인스턴스의 갯수, x의 features
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b


In [16]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [17]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost :", cost_val, "\nPrediction:\n", hy_val)

0 Cost : 167586.56 
Prediction:
 [[-199.47562]
 [-260.01453]
 [-245.44205]
 [-271.3774 ]
 [-199.93152]]
10 Cost : 63.72584 
Prediction:
 [[162.56458]
 [175.18861]
 [183.34093]
 [195.56041]
 [132.03001]]
20 Cost : 61.86201 
Prediction:
 [[163.62952]
 [176.52625]
 [184.62888]
 [196.96687]
 [133.0614 ]]
30 Cost : 61.533527 
Prediction:
 [[163.60233]
 [176.55112]
 [184.62341]
 [196.96486]
 [133.0914 ]]
40 Cost : 61.20678 
Prediction:
 [[163.57191]
 [176.57191]
 [184.61403]
 [196.95853]
 [133.11833]]
50 Cost : 60.881752 
Prediction:
 [[163.54155]
 [176.59265]
 [184.60466]
 [196.95222]
 [133.14516]]
60 Cost : 60.55838 
Prediction:
 [[163.51129]
 [176.61337]
 [184.59532]
 [196.94597]
 [133.17194]]
70 Cost : 60.236885 
Prediction:
 [[163.48111]
 [176.634  ]
 [184.58603]
 [196.93968]
 [133.19864]]
80 Cost : 59.917095 
Prediction:
 [[163.45099]
 [176.65457]
 [184.57672]
 [196.93343]
 [133.22523]]
90 Cost : 59.599113 
Prediction:
 [[163.42099]
 [176.67511]
 [184.56747]
 [196.9272 ]
 [133.25179]]


 [[161.21515]
 [178.18346]
 [183.88661]
 [196.47308]
 [135.19882]]
920 Cost : 38.39097 
Prediction:
 [[161.19113]
 [178.19986]
 [183.87918]
 [196.46817]
 [135.21997]]
930 Cost : 38.189026 
Prediction:
 [[161.16718]
 [178.21625]
 [183.8718 ]
 [196.46329]
 [135.24106]]
940 Cost : 37.98819 
Prediction:
 [[161.14328]
 [178.23257]
 [183.86441]
 [196.45842]
 [135.26208]]
950 Cost : 37.788597 
Prediction:
 [[161.11948]
 [178.24884]
 [183.85706]
 [196.45355]
 [135.28305]]
960 Cost : 37.58994 
Prediction:
 [[161.09572]
 [178.26508]
 [183.84973]
 [196.44872]
 [135.30399]]
970 Cost : 37.392376 
Prediction:
 [[161.07204]
 [178.28128]
 [183.8424 ]
 [196.4439 ]
 [135.32484]]
980 Cost : 37.195885 
Prediction:
 [[161.0484 ]
 [178.29742]
 [183.83511]
 [196.43907]
 [135.34564]]
990 Cost : 37.000385 
Prediction:
 [[161.02483]
 [178.31354]
 [183.82784]
 [196.43428]
 [135.3664 ]]
1000 Cost : 36.80604 
Prediction:
 [[161.00134]
 [178.32959]
 [183.82057]
 [196.42949]
 [135.3871 ]]
1010 Cost : 36.612698 
Pred

1790 Cost : 24.341898 
Prediction:
 [[159.33081]
 [179.47113]
 [183.30402]
 [196.09207]
 [136.85458]]
1800 Cost : 24.215755 
Prediction:
 [[159.31186]
 [179.48409]
 [183.29813]
 [196.08827]
 [136.87119]]
1810 Cost : 24.090199 
Prediction:
 [[159.29295]
 [179.49704]
 [183.2923 ]
 [196.08453]
 [136.88777]]
1820 Cost : 23.965405 
Prediction:
 [[159.27408]
 [179.5099 ]
 [183.28645]
 [196.08073]
 [136.90428]]
1830 Cost : 23.841343 
Prediction:
 [[159.2553 ]
 [179.52274]
 [183.28061]
 [196.07697]
 [136.92076]]
1840 Cost : 23.717882 
Prediction:
 [[159.23653]
 [179.53554]
 [183.27481]
 [196.07323]
 [136.9372 ]]
1850 Cost : 23.59516 
Prediction:
 [[159.21782]
 [179.54831]
 [183.26904]
 [196.0695 ]
 [136.95357]]
1860 Cost : 23.472956 
Prediction:
 [[159.19917]
 [179.56108]
 [183.26326]
 [196.06578]
 [136.96992]]
1870 Cost : 23.351496 
Prediction:
 [[159.18054]
 [179.57378]
 [183.25749]
 [196.06206]
 [136.98619]]
1880 Cost : 23.230742 
Prediction:
 [[159.16202]
 [179.58646]
 [183.25175]
 [196.05

##  파일에서 데이터 불러오기 
### 1. numpy 
\\(H(X) = XW \\)<br>
출처: [Youtube 강의](https://www.youtube.com/watch?v=o2q4QNnoShY)<br>
출처: [DeepLearningZeroToAll](https://github.com/hunkim/DeepLearningZeroToAll/blob/master/lab-04-3-file_input_linear_regression.py)
<br>
파일 : data-01-test-score.csv 


In [18]:
import numpy as np

In [21]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

print(xy)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [22]:
# x와 y를 나누는 방법
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data)
print(y_data)
        

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [24]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)
# 인스턴스 25, x의 feature 3개

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [25]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

In [26]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [27]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
                 "\nPrediction:\n", hy_val)

0 Cost:  1464.5825 
Prediction:
 [[123.5341  ]
 [144.57669 ]
 [144.90208 ]
 [153.21376 ]
 [112.95011 ]
 [ 75.455666]
 [108.73508 ]
 [ 72.46868 ]
 [128.45569 ]
 [108.28846 ]
 [108.315735]
 [103.2307  ]
 [154.42683 ]
 [134.65988 ]
 [108.12105 ]
 [142.65567 ]
 [132.61905 ]
 [128.6123  ]
 [148.55487 ]
 [132.44482 ]
 [128.6967  ]
 [131.30522 ]
 [124.34143 ]
 [135.48903 ]
 [152.6896  ]]
10 Cost:  121.74652 
Prediction:
 [[157.70938]
 [185.69327]
 [185.39183]
 [197.33371]
 [144.299  ]
 [ 98.60905]
 [141.78389]
 [ 97.00067]
 [166.92035]
 [143.97179]
 [140.14462]
 [134.64178]
 [196.23495]
 [169.38376]
 [141.3305 ]
 [184.39798]
 [165.67314]
 [168.27945]
 [188.40286]
 [168.0991 ]
 [167.4492 ]
 [169.89847]
 [161.27869]
 [169.89133]
 [195.28464]]
20 Cost:  120.765945 
Prediction:
 [[157.91513]
 [185.98135]
 [185.65274]
 [197.64131]
 [144.50946]
 [ 98.8052 ]
 [142.03763]
 [ 97.2204 ]
 [167.22772]
 [144.31204]
 [140.37714]
 [134.89804]
 [196.48116]
 [169.55756]
 [141.59409]
 [184.70891]
 [165.82281]


380 Cost:  92.35258 
Prediction:
 [[156.91403 ]
 [186.10135 ]
 [185.02472 ]
 [197.74095 ]
 [144.28342 ]
 [100.00275 ]
 [142.90677 ]
 [ 98.936295]
 [168.60452 ]
 [147.43816 ]
 [140.80406 ]
 [136.20349 ]
 [195.05222 ]
 [167.33705 ]
 [142.75165 ]
 [185.45564 ]
 [163.16673 ]
 [169.8208  ]
 [186.93689 ]
 [166.78644 ]
 [168.67435 ]
 [170.98236 ]
 [162.10095 ]
 [167.21669 ]
 [195.11258 ]]
390 Cost:  91.67751 
Prediction:
 [[156.88873]
 [186.10394]
 [185.0086 ]
 [197.74356]
 [144.27698]
 [100.03296]
 [142.92944]
 [ 98.9811 ]
 [168.63922]
 [147.51779]
 [140.81506]
 [136.23663]
 [195.0155 ]
 [167.2799 ]
 [142.78159]
 [185.47446]
 [163.09805]
 [169.85312]
 [186.89359]
 [166.7478 ]
 [168.69852]
 [171.00235]
 [162.11545]
 [167.14438]
 [195.10059]]
400 Cost:  91.00805 
Prediction:
 [[156.8636 ]
 [186.1065 ]
 [184.9926 ]
 [197.7462 ]
 [144.27052]
 [100.06302]
 [142.95207]
 [ 99.02579]
 [168.67378]
 [147.59708]
 [140.826  ]
 [136.2696 ]
 [194.97897]
 [167.22299]
 [142.81143]
 [185.49316]
 [163.02966]


710 Cost:  72.75777 
Prediction:
 [[156.14552]
 [186.17032]
 [184.52995]
 [197.8253 ]
 [144.06865]
 [100.92233]
 [143.61852]
 [100.34133]
 [169.66092]
 [149.88326]
 [141.1456 ]
 [137.21739]
 [193.91957]
 [165.57013]
 [143.68398]
 [186.02818]
 [161.03491]
 [170.83868]
 [185.60506]
 [165.60059]
 [169.42963]
 [171.59229]
 [162.55914]
 [164.9936 ]
 [194.73415]]
720 Cost:  72.2426 
Prediction:
 [[156.12424 ]
 [186.1719  ]
 [184.51608 ]
 [197.82776 ]
 [144.06207 ]
 [100.94784 ]
 [143.63895 ]
 [100.381615]
 [169.69019 ]
 [149.95172 ]
 [141.15529 ]
 [137.24567 ]
 [193.88766 ]
 [165.5202  ]
 [143.71048 ]
 [186.04407 ]
 [160.97443 ]
 [170.86801 ]
 [185.56766 ]
 [165.56738 ]
 [169.4512  ]
 [171.60922 ]
 [162.57239 ]
 [164.9312  ]
 [194.7232  ]]
730 Cost:  71.73166 
Prediction:
 [[156.10307]
 [186.17345]
 [184.50224]
 [197.83025]
 [144.05553]
 [100.97321]
 [143.65929]
 [100.42178]
 [169.71933]
 [150.01988]
 [141.16495]
 [137.27383]
 [193.85588]
 [165.47054]
 [143.7369 ]
 [186.05984]
 [160.91418]
 

1000 Cost:  59.39534 
Prediction:
 [[155.57176]
 [186.20564]
 [184.15157]
 [197.89548]
 [143.87788]
 [101.61085]
 [144.18518]
 [101.45868]
 [170.45152]
 [151.74669]
 [141.41225]
 [137.98523]
 [193.04689]
 [164.20294]
 [144.4149 ]
 [186.45697]
 [159.37192]
 [171.65547]
 [184.58472]
 [164.69681]
 [170.02644]
 [172.05017]
 [162.92914]
 [163.2928 ]
 [194.4293 ]]
1010 Cost:  58.988297 
Prediction:
 [[155.55351]
 [186.2065 ]
 [184.1394 ]
 [197.89786]
 [143.8713 ]
 [101.63279]
 [144.20383]
 [101.4954 ]
 [170.47673]
 [151.80664]
 [141.42096]
 [138.00984]
 [193.01868]
 [164.15866]
 [144.43877]
 [186.47064]
 [159.31781]
 [171.68242]
 [184.55182]
 [164.66777]
 [170.04602]
 [172.06479]
 [162.94142]
 [163.238  ]
 [194.41927]]
1020 Cost:  58.584473 
Prediction:
 [[155.53537 ]
 [186.20734 ]
 [184.12726 ]
 [197.9002  ]
 [143.86473 ]
 [101.654625]
 [144.22238 ]
 [101.53199 ]
 [170.5018  ]
 [151.8663  ]
 [141.4296  ]
 [138.03436 ]
 [192.99057 ]
 [164.11452 ]
 [144.46254 ]
 [186.48424 ]
 [159.2639  ]
 [1

1310 Cost:  48.183853 
Prediction:
 [[155.04889]
 [186.22198]
 [183.79791]
 [197.96657]
 [143.67422]
 [102.24024]
 [144.73624]
 [102.54406]
 [171.17395]
 [153.4822 ]
 [141.66673]
 [138.6957 ]
 [192.22502]
 [162.90991]
 [145.11533]
 [186.84904]
 [157.78625]
 [172.45563]
 [183.6293 ]
 [163.85509]
 [170.60275]
 [172.46991]
 [163.29381]
 [161.70248]
 [194.12968]]
1320 Cost:  47.8666 
Prediction:
 [[155.03342 ]
 [186.22218 ]
 [183.7873  ]
 [197.96878 ]
 [143.66766 ]
 [102.258896]
 [144.75311 ]
 [102.57733 ]
 [171.19534 ]
 [153.53415 ]
 [141.67444 ]
 [138.71687 ]
 [192.20027 ]
 [162.87083 ]
 [145.13661 ]
 [186.86064 ]
 [157.73816 ]
 [172.48026 ]
 [183.6006  ]
 [163.82986 ]
 [170.62036 ]
 [172.48238 ]
 [163.30507 ]
 [161.65474 ]
 [194.12044 ]]
1330 Cost:  47.551895 
Prediction:
 [[155.01805]
 [186.22235]
 [183.77672]
 [197.97098]
 [143.66113]
 [102.27743]
 [144.76996]
 [102.61049]
 [171.21661]
 [153.58588]
 [141.68214]
 [138.73796]
 [192.17558]
 [162.83194]
 [145.15785]
 [186.8722 ]
 [157.690

1620 Cost:  39.43641 
Prediction:
 [[154.60661 ]
 [186.22023 ]
 [183.49013 ]
 [198.03362 ]
 [143.47264 ]
 [102.774475]
 [145.23628 ]
 [103.527985]
 [171.78685 ]
 [154.9867  ]
 [141.89322 ]
 [139.30711 ]
 [191.50381 ]
 [161.76997 ]
 [145.74136 ]
 [187.18193 ]
 [156.37625 ]
 [173.1872  ]
 [182.79611 ]
 [163.12537 ]
 [171.12198 ]
 [172.82736 ]
 [163.62918 ]
 [160.31775 ]
 [193.85478 ]]
1630 Cost:  39.188583 
Prediction:
 [[154.59357]
 [186.21988]
 [183.48088]
 [198.03574]
 [143.4662 ]
 [102.79029]
 [145.25162]
 [103.55815]
 [171.80496]
 [155.03172]
 [141.90009]
 [139.32533]
 [191.48206]
 [161.73553]
 [145.76039]
 [187.19177]
 [156.33345]
 [173.20972]
 [182.7711 ]
 [163.10352]
 [171.13783]
 [172.83795]
 [163.63953]
 [160.27618]
 [193.8463 ]]
1640 Cost:  38.942673 
Prediction:
 [[154.5806 ]
 [186.21957]
 [183.47171]
 [198.03783]
 [143.45978]
 [102.80601]
 [145.26694]
 [103.58823]
 [171.82301]
 [155.07658]
 [141.90695]
 [139.34349]
 [191.46043]
 [161.70125]
 [145.7794 ]
 [187.20158]
 [156.29

In [29]:
print("Your score will be ", sess.run(hypothesis,
                                     feed_dict={X: [[100, 70, 101]]}))

Your score will be  [[183.05507]]


너의 final점수는 183일 것이다. 

In [30]:
# 친구1과 친구2의 점수
print("Other scores will be ", sess.run(hypothesis, 
                                       feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Other scores will be  [[139.53497]
 [188.6085 ]]


### 2. Queue Runners
파일이 굉장히 크면, 메모리에 한번에 올리는 것이 힘들다. 
**Queue Runners**는 하나의 파일이 아니라 여러개의 파일에서 읽어올 수 있다. <br>
학습을 시킬 때는 한번에 **전체 데이터**가 필요한 것이 **어떤 batch만큼** 읽어와서, 학습을 시킨다. <br>
참고: [Quere Runners](https://www.tensorflow.org/programmers_guide/datasets)
1. 파일 name을 리스트
우리가 가지고 있는 파일은 몇 개 인가?
2. 어떤 식으로 읽을지 정의
3. value를 읽어왔으면, value값을 어떻게 parsing할지 정의
decode_csv

In [34]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv', 'data-02-test-score.csv', 'data-03-test-score.csv'],
    shuffle=False, name='filename_queue')
print(filename_queue)

In [39]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)
print(key, value)

Tensor("ReaderReadV2_4:0", shape=(), dtype=string) Tensor("ReaderReadV2_4:1", shape=(), dtype=string)


In [42]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)
print(xy)

[<tf.Tensor 'DecodeCSV_1:0' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_1:1' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_1:2' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_1:3' shape=() dtype=float32>]


In [53]:
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
print(train_x_batch)
print(train_y_batch)
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

Tensor("batch_5:0", shape=(10, 3), dtype=float32)
Tensor("batch_5:1", shape=(10, 1), dtype=float32)


In [46]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [48]:
sess = tf.Session(), 
sess.run(tf.global_variables_initializer())

In [49]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)

0 Cost:  9559.545 
Prediction
 [[79.46881 ]
 [58.758198]
 [83.29903 ]
 [87.19789 ]
 [67.44292 ]
 [51.631832]
 [82.46264 ]
 [60.319237]
 [52.64154 ]
 [77.03049 ]]
10 Cost:  94.60923 
Prediction
 [[138.51463]
 [173.59554]
 [166.26059]
 [147.43486]
 [173.00954]
 [179.40239]
 [162.29413]
 [134.11436]
 [190.70679]
 [141.20366]]
20 Cost:  83.40703 
Prediction
 [[139.18588]
 [174.37265]
 [167.07236]
 [148.16646]
 [173.75562]
 [180.11807]
 [163.01537]
 [134.85161]
 [191.52454]
 [141.90546]]
30 Cost:  82.71179 
Prediction
 [[139.225  ]
 [174.39395]
 [167.12292]
 [148.21693]
 [173.76323]
 [180.09848]
 [163.03246]
 [134.93059]
 [191.52974]
 [141.95464]]
40 Cost:  82.090225 
Prediction
 [[139.25963]
 [174.41002]
 [167.16806]
 [148.26254]
 [173.7658 ]
 [180.07393]
 [163.0447 ]
 [135.00471]
 [191.52937]
 [141.99913]]
50 Cost:  81.474815 
Prediction
 [[139.29399]
 [174.426  ]
 [167.21292]
 [148.30789]
 [173.76833]
 [180.04944]
 [163.05685]
 [135.07848]
 [191.52896]
 [142.0434 ]]
60 Cost:  80.864845 


520 Cost:  57.902576 
Prediction
 [[140.71251]
 [175.13788]
 [169.10405]
 [150.2237 ]
 [173.89423]
 [179.00977]
 [163.58884]
 [138.1879 ]
 [191.49704]
 [143.92427]]
530 Cost:  57.49923 
Prediction
 [[140.73883]
 [175.15222]
 [169.13998]
 [150.2602 ]
 [173.89702]
 [178.98985]
 [163.59937]
 [138.24702]
 [191.49615]
 [143.96034]]
540 Cost:  57.099518 
Prediction
 [[140.76498]
 [175.16652]
 [169.17575]
 [150.29654]
 [173.89983]
 [178.97   ]
 [163.60986]
 [138.30585]
 [191.49522]
 [143.99623]]
550 Cost:  56.70332 
Prediction
 [[140.791  ]
 [175.18077]
 [169.21135]
 [150.33269]
 [173.90263]
 [178.95026]
 [163.62033]
 [138.36443]
 [191.49431]
 [144.03197]]
560 Cost:  56.310486 
Prediction
 [[140.81688]
 [175.195  ]
 [169.24677]
 [150.36871]
 [173.90546]
 [178.93057]
 [163.63077]
 [138.42271]
 [191.49336]
 [144.06757]]
570 Cost:  55.921165 
Prediction
 [[140.8426 ]
 [175.2092 ]
 [169.28204]
 [150.40454]
 [173.90826]
 [178.911  ]
 [163.64116]
 [138.48074]
 [191.49243]
 [144.10301]]
580 Cost:  5

1050 Cost:  40.710148 
Prediction
 [[141.91943]
 [175.85336]
 [170.79614]
 [151.9476 ]
 [174.04659]
 [178.06233]
 [164.10577]
 [140.97368]
 [191.43912]
 [145.63843]]
1060 Cost:  40.45555 
Prediction
 [[141.93886]
 [175.86604]
 [170.82425]
 [151.97633]
 [174.04955]
 [178.04643]
 [164.11476]
 [141.01997]
 [191.43788]
 [145.66722]]
1070 Cost:  40.203228 
Prediction
 [[141.95815]
 [175.87868]
 [170.85222]
 [152.00493]
 [174.05246]
 [178.0306 ]
 [164.12373]
 [141.06606]
 [191.43661]
 [145.69588]]
1080 Cost:  39.953014 
Prediction
 [[141.97734]
 [175.89128]
 [170.88005]
 [152.0334 ]
 [174.05539]
 [178.01482]
 [164.13269]
 [141.11192]
 [191.43535]
 [145.72441]]
1090 Cost:  39.705128 
Prediction
 [[141.9964 ]
 [175.90387]
 [170.90776]
 [152.0617 ]
 [174.05832]
 [177.99911]
 [164.14159]
 [141.15756]
 [191.43405]
 [145.7528 ]]
1100 Cost:  39.45912 
Prediction
 [[142.01538]
 [175.91643]
 [170.93533]
 [152.08994]
 [174.06125]
 [177.98347]
 [164.15048]
 [141.20302]
 [191.4328 ]
 [145.78111]]
1110 C

1560 Cost:  30.143383 
Prediction
 [[142.77682]
 [176.46332]
 [172.07516]
 [153.25922]
 [174.19673]
 [177.33104]
 [164.53252]
 [143.0825 ]
 [191.36948]
 [146.96162]]
1570 Cost:  29.978409 
Prediction
 [[142.79117]
 [176.47458]
 [172.09735]
 [153.28204]
 [174.19968]
 [177.31824]
 [164.54028]
 [143.11911]
 [191.36804]
 [146.98485]]
1580 Cost:  29.814926 
Prediction
 [[142.80542]
 [176.4858 ]
 [172.11942]
 [153.30476]
 [174.20262]
 [177.30545]
 [164.548  ]
 [143.15555]
 [191.36658]
 [147.00795]]
1590 Cost:  29.652878 
Prediction
 [[142.81955]
 [176.49698]
 [172.14139]
 [153.32738]
 [174.20557]
 [177.29272]
 [164.5557 ]
 [143.1918 ]
 [191.36511]
 [147.03096]]
1600 Cost:  29.491964 
Prediction
 [[142.83366]
 [176.50816]
 [172.16327]
 [153.3499 ]
 [174.20851]
 [177.28008]
 [164.5634 ]
 [143.2279 ]
 [191.36365]
 [147.0539 ]]
1610 Cost:  29.332544 
Prediction
 [[142.84764]
 [176.5193 ]
 [172.18504]
 [153.37233]
 [174.21146]
 [177.26747]
 [164.57106]
 [143.26382]
 [191.36217]
 [147.07672]]
1620

In [50]:
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[207.63976]]
Other scores will be  [[187.09529]
 [167.10846]]


Shuffle_batch? 